"""empty message

Revision ID: 161013693654
Revises: 
Create Date: 2019-09-09 13:18:36.652744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '161013693654'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('f_lags')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('f_lags',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('post_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name='f_lags_post_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='f_lags_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='f_lags_pkey')
    )
    # ### end Alembic commands ###
